import {
  BadRequestException,
  Injectable,
  InternalServerErrorException,
} from '@nestjs/common';
import { LogReport } from './interface/log-report.interface';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { ErrorCodes } from '../../enum/error-code.enum';
import { FilterAndPaginationLogReportDto } from './dto/log-report.dto';
import { ResponsePayload } from '../../interfaces/response-payload.interface';
import { UtilsService } from '../utils/utils.service';
import { Vendor } from '../../pages/vendor/interfaces/vendor.interface';
import { Shop } from '../../pages/shop/interfaces/shop.interface';
const ObjectId = Types.ObjectId;

@Injectable()
export class LogReportService {
  constructor(
    private utilsService: UtilsService,
    @InjectModel('LogReport')
    private readonly logReportModel: Model<LogReport>,
    @InjectModel('Shop') private readonly shopModel: Model<Shop>,
  ) {}

  /**
   * Log Report Generated by Softlab IT -> MD IQBAL HOSSEN SAZIB
   * Usages:
   * -Schema Name 'collection' not allowed on Mongo DB
   * - Add Provider [LogReportService] in module of page
   * - Add Mongo DB Collection Schema in module of page
   * createLogReport()
   */

  async createLogReport(data: any) {
    try {
      const baseData = {
        dateString: this.utilsService.getDateString(new Date()),
        time: this.utilsService.getCurrentTime(),
        month: this.utilsService.getDateMonth(new Date(), false),
        year: this.utilsService.getDateYear(new Date()),
      };
      const saveData = new this.logReportModel({ ...baseData, ...data });
      await saveData.save();
      return {
        success: true,
        message: 'Success',
        data: null,
      } as ResponsePayload;
    } catch (error) {
      console.log(error);
    }
  }

  /**
   * API DATA
   * getAllLogReports()
   */

  async getAllLogReportByShop(
    vendor: Vendor,
    shop: string,
    filterAndPaginationLogReportDto: FilterAndPaginationLogReportDto,
    searchQuery?: string,
  ): Promise<ResponsePayload> {
    try {
      const fShop = await this.shopModel.exists({
        _id: shop,
        'users._id': vendor._id,
      });

      if (!fShop) {
        return {
          success: false,
          message: 'Sorry! you have no access in this shop',
        } as ResponsePayload;
      }

      // Modify Filter
      const { filter } = filterAndPaginationLogReportDto;
      filterAndPaginationLogReportDto.filter = {
        ...filter,
        ...{ shop: shop },
      };

      return this.getAllLogReports(
        filterAndPaginationLogReportDto,
        searchQuery,
      );
    } catch (error) {
      console.log(error);
      throw new InternalServerErrorException(error.message);
    }
  }

  async getAllLogReports(
    filterAdmissionDto: FilterAndPaginationLogReportDto,
    searchQuery?: string,
  ): Promise<ResponsePayload> {
    const { filter } = filterAdmissionDto;
    const { pagination } = filterAdmissionDto;
    const { sort } = filterAdmissionDto;
    const { select } = filterAdmissionDto;

    // Modify Id as Object ID
    if (filter && filter['vendor._id']) {
      filter['vendor._id'] = new ObjectId(filter['vendor._id']);
    }
    if (filter['shop']) {
      filter['shop'] = new ObjectId(filter['shop']);
    }

    // Essential Variables
    const aggregateSadmissiones = [];
    let mFilter = {};
    let mSort = {};
    let mSelect = {};
    let mPagination = {};

    // Match
    if (filter) {
      mFilter = { ...mFilter, ...filter };
    }
    if (searchQuery) {
      mFilter = {
        $and: [
          mFilter,
          {
            $or: [{ description: { $regex: searchQuery, $options: 'i' } }],
          },
        ],
      };
    }
    // Sort
    if (sort) {
      mSort = sort;
    } else {
      mSort = { createdAt: -1 };
    }

    // Select
    if (select) {
      mSelect = { ...select };
    } else {
      mSelect = { name: 1 };
    }

    // Finalize
    if (Object.keys(mFilter).length) {
      aggregateSadmissiones.push({ $match: mFilter });
    }

    if (Object.keys(mSort).length) {
      aggregateSadmissiones.push({ $sort: mSort });
    }

    if (!pagination) {
      aggregateSadmissiones.push({ $project: mSelect });
    }

    // Pagination
    if (pagination) {
      if (Object.keys(mSelect).length) {
        mPagination = {
          $facet: {
            metadata: [{ $count: 'total' }],
            data: [
              {
                $skip: pagination.pageSize * pagination.currentPage,
              } /* IF PAGE START FROM 0 OR (pagination.currentPage - 1) IF PAGE 1*/,
              { $limit: pagination.pageSize },
              { $project: mSelect },
            ],
          },
        };
      } else {
        mPagination = {
          $facet: {
            metadata: [{ $count: 'total' }],
            data: [
              {
                $skip: pagination.pageSize * pagination.currentPage,
              } /* IF PAGE START FROM 0 OR (pagination.currentPage - 1) IF PAGE 1*/,
              { $limit: pagination.pageSize },
            ],
          },
        };
      }

      aggregateSadmissiones.push(mPagination);

      aggregateSadmissiones.push({
        $project: {
          data: 1,
          count: { $arrayElemAt: ['$metadata.total', 0] },
        },
      });
    }

    try {
      const dataAggregates = await this.logReportModel.aggregate(
        aggregateSadmissiones,
      );
      if (pagination) {
        return {
          ...{ ...dataAggregates[0] },
          ...{ success: true, message: 'Success' },
        } as ResponsePayload;
      } else {
        return {
          data: dataAggregates,
          success: true,
          message: 'Success',
          count: dataAggregates.length,
        } as ResponsePayload;
      }
    } catch (err) {
      console.log(err);
      if (err.code && err.code.toString() === ErrorCodes.PROJECTION_MISMATCH) {
        throw new BadRequestException('Error! Admissionion mismatch');
      } else {
        throw new InternalServerErrorException(err.message);
      }
    }
  }

  async deleteMultipleLogReportsById(
    ids: string[],
    checkUsage?: boolean,
  ): Promise<ResponsePayload> {
    try {
      const mIds = ids.map((m) => new ObjectId(m));
      await this.logReportModel.deleteMany({ _id: mIds });
      return {
        success: true,
        message: 'Success',
      } as ResponsePayload;
    } catch (err) {
      throw new InternalServerErrorException(err.message);
    }
  }
}
