export enum OrderStatus {
  NONE = 0,
  PENDING = 1,
  CONFIRM = 2,
  PROCESSING = 3,
  SHIPPING = 4,
  DELIVERED = 5,
  CANCEL = 6,
  REFUND = 7,
  ReadToPrint = 8,
  PrintInvoice = 9,
  ReadyToPackaging = 10,
  Packaging = 11,
  ReadyToShipped = 12,
  HoldInvoice = 13,
}

export enum CourierOrderStatus {
  NONE = 0,
  PENDING = 1,
  CONFIRM = 2,
  PROCESSING = 3,
  SHIPPING = 4,
  DELIVERED = 5,
  CANCEL = 6,
  REFUND = 7,
  ReadToPrint = 8,
  PrintInvoice = 9,
  ReadyToPackaging = 10,
  Packaging = 11,
  ReadyToShipped = 12,
  HoldInvoice = 13,
}
